package nostrability.schemata;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

public final class Schemata {
    private static final Map<String, String> REGISTRY = new LinkedHashMap<>();
    private static final Map<String, String> CACHE = new ConcurrentHashMap<>();

    static {
        REGISTRY.put("kind0ContentSchema", "schemas/nips/nip-01/kind-0/schema.content.json");
        REGISTRY.put("kind0Schema", "schemas/nips/nip-01/kind-0/schema.json");
        REGISTRY.put("kind1Schema", "schemas/nips/nip-01/kind-1/schema.json");
        REGISTRY.put("clientCloseSchema", "schemas/nips/nip-01/messages/client-close/schema.json");
        REGISTRY.put("clientEventSchema", "schemas/nips/nip-01/messages/client-event/schema.json");
        REGISTRY.put("clientReqSchema", "schemas/nips/nip-01/messages/client-req/schema.json");
        REGISTRY.put("filterSchema", "schemas/nips/nip-01/messages/filter/schema.json");
        REGISTRY.put("relayClosedSchema", "schemas/nips/nip-01/messages/relay-closed/schema.json");
        REGISTRY.put("relayEoseSchema", "schemas/nips/nip-01/messages/relay-eose/schema.json");
        REGISTRY.put("relayEventSchema", "schemas/nips/nip-01/messages/relay-event/schema.json");
        REGISTRY.put("relayNoticeSchema", "schemas/nips/nip-01/messages/relay-notice/schema.json");
        REGISTRY.put("relayOkSchema", "schemas/nips/nip-01/messages/relay-ok/schema.json");
        REGISTRY.put("noteSchema", "schemas/nips/nip-01/note/schema.json");
        REGISTRY.put("noteUnsignedSchema", "schemas/nips/nip-01/note-unsigned/schema.json");
        REGISTRY.put("secp256k1Schema", "schemas/nips/nip-01/secp256k1/schema.json");
        REGISTRY.put("aTagSchema", "schemas/nips/nip-01/tag/a/schema.json");
        REGISTRY.put("dTagSchema", "schemas/nips/nip-01/tag/d/schema.json");
        REGISTRY.put("eTagSchema", "schemas/nips/nip-01/tag/e/schema.json");
        REGISTRY.put("pTagSchema", "schemas/nips/nip-01/tag/p/schema.json");
        REGISTRY.put("tagSchema", "schemas/nips/nip-01/tag/schema.json");
        REGISTRY.put("tTagSchema", "schemas/nips/nip-01/tag/t/schema.json");
        REGISTRY.put("kind3ContentSchema", "schemas/nips/nip-02/kind-3/schema.content.json");
        REGISTRY.put("kind3Schema", "schemas/nips/nip-02/kind-3/schema.json");
        REGISTRY.put("kind4Schema", "schemas/nips/nip-04/kind-4/schema.json");
        REGISTRY.put("identifierSchema", "schemas/nips/nip-05/identifier/schema.json");
        REGISTRY.put("wellKnownSchema", "schemas/nips/nip-05/well-known/schema.json");
        REGISTRY.put("kind5Schema", "schemas/nips/nip-09/kind-5/schema.json");
        REGISTRY.put("nip11Schema", "schemas/nips/nip-11/schema.json");
        REGISTRY.put("kind10050Schema", "schemas/nips/nip-17/kind-10050/schema.json");
        REGISTRY.put("kind14Schema", "schemas/nips/nip-17/kind-14/schema.json");
        REGISTRY.put("kind15Schema", "schemas/nips/nip-17/kind-15/schema.json");
        REGISTRY.put("blurhashTagSchema", "schemas/nips/nip-17/tag/blurhash/schema.json");
        REGISTRY.put("decryptionkeyTagSchema", "schemas/nips/nip-17/tag/decryption-key/schema.json");
        REGISTRY.put("decryptionnonceTagSchema", "schemas/nips/nip-17/tag/decryption-nonce/schema.json");
        REGISTRY.put("dimTagSchema", "schemas/nips/nip-17/tag/dim/schema.json");
        REGISTRY.put("encryptionalgorithmTagSchema", "schemas/nips/nip-17/tag/encryption-algorithm/schema.json");
        REGISTRY.put("fallbackTagSchema", "schemas/nips/nip-17/tag/fallback/schema.json");
        REGISTRY.put("filetypeTagSchema", "schemas/nips/nip-17/tag/file-type/schema.json");
        REGISTRY.put("oxTagSchema", "schemas/nips/nip-17/tag/ox/schema.json");
        REGISTRY.put("relayTagSchema", "schemas/nips/nip-17/tag/relay/schema.json");
        REGISTRY.put("sizeTagSchema", "schemas/nips/nip-17/tag/size/schema.json");
        REGISTRY.put("subjectTagSchema", "schemas/nips/nip-17/tag/subject/schema.json");
        REGISTRY.put("thumbTagSchema", "schemas/nips/nip-17/tag/thumb/schema.json");
        REGISTRY.put("xTagSchema", "schemas/nips/nip-17/tag/x/schema.json");
        REGISTRY.put("kind16Schema", "schemas/nips/nip-18/kind-16/schema.json");
        REGISTRY.put("kind6Schema", "schemas/nips/nip-18/kind-6/schema.json");
        REGISTRY.put("kTagSchema", "schemas/nips/nip-18/tag/k/schema.json");
        REGISTRY.put("qTagSchema", "schemas/nips/nip-18/tag/q/schema.json");
        REGISTRY.put("kind1111Schema", "schemas/nips/nip-22/kind-1111/schema.json");
        REGISTRY.put("ATagSchema", "schemas/nips/nip-22/tag/_A/schema.json");
        REGISTRY.put("ETagSchema", "schemas/nips/nip-22/tag/_E/schema.json");
        REGISTRY.put("KTagSchema", "schemas/nips/nip-22/tag/_K/schema.json");
        REGISTRY.put("PTagSchema", "schemas/nips/nip-22/tag/_P/schema.json");
        REGISTRY.put("kind30023Schema", "schemas/nips/nip-23/kind-30023/schema.json");
        REGISTRY.put("kind30024Schema", "schemas/nips/nip-23/kind-30024/schema.json");
        REGISTRY.put("publishedatTagSchema", "schemas/nips/nip-23/tag/published_at/schema.json");
        REGISTRY.put("kind17Schema", "schemas/nips/nip-25/kind-17/schema.json");
        REGISTRY.put("kind7Schema", "schemas/nips/nip-25/kind-7/schema.json");
        REGISTRY.put("ereactTagSchema", "schemas/nips/nip-25/tag/e-react/schema.json");
        REGISTRY.put("emojiTagSchema", "schemas/nips/nip-25/tag/emoji/schema.json");
        REGISTRY.put("kind1985Schema", "schemas/nips/nip-32/kind-1985/schema.json");
        REGISTRY.put("LTagSchema", "schemas/nips/nip-32/tag/L/schema.json");
        REGISTRY.put("lTagSchema", "schemas/nips/nip-32/tag/l/schema.json");
        REGISTRY.put("kind1617Schema", "schemas/nips/nip-34/kind-1617/schema.json");
        REGISTRY.put("kind1621Schema", "schemas/nips/nip-34/kind-1621/schema.json");
        REGISTRY.put("kind1630Schema", "schemas/nips/nip-34/kind-1630/schema.json");
        REGISTRY.put("kind1631Schema", "schemas/nips/nip-34/kind-1631/schema.json");
        REGISTRY.put("kind1632Schema", "schemas/nips/nip-34/kind-1632/schema.json");
        REGISTRY.put("kind1633Schema", "schemas/nips/nip-34/kind-1633/schema.json");
        REGISTRY.put("kind30617Schema", "schemas/nips/nip-34/kind-30617/schema.json");
        REGISTRY.put("kind30618Schema", "schemas/nips/nip-34/kind-30618/schema.json");
        REGISTRY.put("appliedascommitsTagSchema", "schemas/nips/nip-34/tag/applied-as-commits/schema.json");
        REGISTRY.put("cloneTagSchema", "schemas/nips/nip-34/tag/clone/schema.json");
        REGISTRY.put("commitTagSchema", "schemas/nips/nip-34/tag/commit/schema.json");
        REGISTRY.put("commitpgpsigTagSchema", "schemas/nips/nip-34/tag/commit-pgp-sig/schema.json");
        REGISTRY.put("committerTagSchema", "schemas/nips/nip-34/tag/committer/schema.json");
        REGISTRY.put("erootTagSchema", "schemas/nips/nip-34/tag/e-root/schema.json");
        REGISTRY.put("estatusreplyTagSchema", "schemas/nips/nip-34/tag/e-status-reply/schema.json");
        REGISTRY.put("headTagSchema", "schemas/nips/nip-34/tag/head/schema.json");
        REGISTRY.put("maintainersTagSchema", "schemas/nips/nip-34/tag/maintainers/schema.json");
        REGISTRY.put("mergecommitTagSchema", "schemas/nips/nip-34/tag/merge-commit/schema.json");
        REGISTRY.put("nameTagSchema", "schemas/nips/nip-34/tag/name/schema.json");
        REGISTRY.put("parentcommitTagSchema", "schemas/nips/nip-34/tag/parent-commit/schema.json");
        REGISTRY.put("reucTagSchema", "schemas/nips/nip-34/tag/r-euc/schema.json");
        REGISTRY.put("refTagSchema", "schemas/nips/nip-34/tag/ref/schema.json");
        REGISTRY.put("webTagSchema", "schemas/nips/nip-34/tag/web/schema.json");
        REGISTRY.put("contentwarningTagSchema", "schemas/nips/nip-36/tag/content-warning/schema.json");
        REGISTRY.put("kind30315Schema", "schemas/nips/nip-38/kind-30315/schema.json");
        REGISTRY.put("expirationTagSchema", "schemas/nips/nip-38/tag/expiration/schema.json");
        REGISTRY.put("statustypeTagSchema", "schemas/nips/nip-38/tag/status-type/schema.json");
        REGISTRY.put("clientAuthSchema", "schemas/nips/nip-40/messages/client-auth/schema.json");
        REGISTRY.put("relayAuthSchema", "schemas/nips/nip-40/messages/relay-auth/schema.json");
        REGISTRY.put("kind22242Schema", "schemas/nips/nip-42/kind-22242/schema.json");
        REGISTRY.put("challengeTagSchema", "schemas/nips/nip-42/tag/challenge/schema.json");
        REGISTRY.put("kind31922Schema", "schemas/nips/nip-52/kind-31922/schema.json");
        REGISTRY.put("kind31923Schema", "schemas/nips/nip-52/kind-31923/schema.json");
        REGISTRY.put("kind31924Schema", "schemas/nips/nip-52/kind-31924/schema.json");
        REGISTRY.put("kind31925Schema", "schemas/nips/nip-52/kind-31925/schema.json");
        REGISTRY.put("endtzidTagSchema", "schemas/nips/nip-52/tag/end_tzid/schema.json");
        REGISTRY.put("fbTagSchema", "schemas/nips/nip-52/tag/fb/schema.json");
        REGISTRY.put("gTagSchema", "schemas/nips/nip-52/tag/g/schema.json");
        REGISTRY.put("locationTagSchema", "schemas/nips/nip-52/tag/location/schema.json");
        REGISTRY.put("starttzidTagSchema", "schemas/nips/nip-52/tag/start_tzid/schema.json");
        REGISTRY.put("statusTagSchema", "schemas/nips/nip-52/tag/status/schema.json");
        REGISTRY.put("kind10312Schema", "schemas/nips/nip-53/kind-10312/schema.json");
        REGISTRY.put("kind1311Schema", "schemas/nips/nip-53/kind-1311/schema.json");
        REGISTRY.put("kind30311Schema", "schemas/nips/nip-53/kind-30311/schema.json");
        REGISTRY.put("kind30312Schema", "schemas/nips/nip-53/kind-30312/schema.json");
        REGISTRY.put("kind30313Schema", "schemas/nips/nip-53/kind-30313/schema.json");
        REGISTRY.put("aliveTagSchema", "schemas/nips/nip-53/tag/a-live/schema.json");
        REGISTRY.put("aroomTagSchema", "schemas/nips/nip-53/tag/a-room/schema.json");
        REGISTRY.put("currentparticipantsTagSchema", "schemas/nips/nip-53/tag/current_participants/schema.json");
        REGISTRY.put("endpointTagSchema", "schemas/nips/nip-53/tag/endpoint/schema.json");
        REGISTRY.put("endsTagSchema", "schemas/nips/nip-53/tag/ends/schema.json");
        REGISTRY.put("handTagSchema", "schemas/nips/nip-53/tag/hand/schema.json");
        REGISTRY.put("imageTagSchema", "schemas/nips/nip-53/tag/image/schema.json");
        REGISTRY.put("pinnedTagSchema", "schemas/nips/nip-53/tag/pinned/schema.json");
        REGISTRY.put("recordingTagSchema", "schemas/nips/nip-53/tag/recording/schema.json");
        REGISTRY.put("relaysTagSchema", "schemas/nips/nip-53/tag/relays/schema.json");
        REGISTRY.put("roomTagSchema", "schemas/nips/nip-53/tag/room/schema.json");
        REGISTRY.put("serviceTagSchema", "schemas/nips/nip-53/tag/service/schema.json");
        REGISTRY.put("startsTagSchema", "schemas/nips/nip-53/tag/starts/schema.json");
        REGISTRY.put("statusliveTagSchema", "schemas/nips/nip-53/tag/status-live/schema.json");
        REGISTRY.put("statusroomTagSchema", "schemas/nips/nip-53/tag/status-room/schema.json");
        REGISTRY.put("streamingTagSchema", "schemas/nips/nip-53/tag/streaming/schema.json");
        REGISTRY.put("summaryTagSchema", "schemas/nips/nip-53/tag/summary/schema.json");
        REGISTRY.put("titleTagSchema", "schemas/nips/nip-53/tag/title/schema.json");
        REGISTRY.put("totalparticipantsTagSchema", "schemas/nips/nip-53/tag/total_participants/schema.json");
        REGISTRY.put("kind1984Schema", "schemas/nips/nip-56/kind-1984/schema.json");
        REGISTRY.put("serverTagSchema", "schemas/nips/nip-56/tag/server/schema.json");
        REGISTRY.put("kind9734Schema", "schemas/nips/nip-57/kind-9734/schema.json");
        REGISTRY.put("kind9735Schema", "schemas/nips/nip-57/kind-9735/schema.json");
        REGISTRY.put("amountTagSchema", "schemas/nips/nip-57/tag/amount/schema.json");
        REGISTRY.put("bolt11TagSchema", "schemas/nips/nip-57/tag/bolt11/schema.json");
        REGISTRY.put("descriptionTagSchema", "schemas/nips/nip-57/tag/description/schema.json");
        REGISTRY.put("lnurlTagSchema", "schemas/nips/nip-57/tag/lnurl/schema.json");
        REGISTRY.put("preimageTagSchema", "schemas/nips/nip-57/tag/preimage/schema.json");
        REGISTRY.put("kind1059Schema", "schemas/nips/nip-59/kind-1059/schema.json");
        REGISTRY.put("kind13Schema", "schemas/nips/nip-59/kind-13/schema.json");
        REGISTRY.put("kind10019Schema", "schemas/nips/nip-61/kind-10019/schema.json");
        REGISTRY.put("kind7376Schema", "schemas/nips/nip-61/kind-7376/schema.json");
        REGISTRY.put("kind9321Schema", "schemas/nips/nip-61/kind-9321/schema.json");
        REGISTRY.put("eredeemedTagSchema", "schemas/nips/nip-61/tag/e-redeemed/schema.json");
        REGISTRY.put("mintTagSchema", "schemas/nips/nip-61/tag/mint/schema.json");
        REGISTRY.put("proofTagSchema", "schemas/nips/nip-61/tag/proof/schema.json");
        REGISTRY.put("pubkeyTagSchema", "schemas/nips/nip-61/tag/pubkey/schema.json");
        REGISTRY.put("uTagSchema", "schemas/nips/nip-61/tag/u/schema.json");
        REGISTRY.put("kind10002Schema", "schemas/nips/nip-65/kind-10002/schema.json");
        REGISTRY.put("rTagSchema", "schemas/nips/nip-65/tag/r/schema.json");
        REGISTRY.put("kind20Schema", "schemas/nips/nip-68/kind-20/schema.json");
        REGISTRY.put("imetaTagSchema", "schemas/nips/nip-68/tag/imeta/schema.json");
        REGISTRY.put("iTagSchema", "schemas/nips/nip-73/tag/i/schema.json");
        REGISTRY.put("kind30078Schema", "schemas/nips/nip-78/kind-30078/schema.json");
        REGISTRY.put("kind9802Schema", "schemas/nips/nip-84/kind-9802/schema.json");
        REGISTRY.put("commentTagSchema", "schemas/nips/nip-84/tag/comment/schema.json");
        REGISTRY.put("contextTagSchema", "schemas/nips/nip-84/tag/context/schema.json");
        REGISTRY.put("kind1018Schema", "schemas/nips/nip-88/kind-1018/schema.json");
        REGISTRY.put("kind1068Schema", "schemas/nips/nip-88/kind-1068/schema.json");
        REGISTRY.put("endsAtTagSchema", "schemas/nips/nip-88/tag/endsAt/schema.json");
        REGISTRY.put("optionTagSchema", "schemas/nips/nip-88/tag/option/schema.json");
        REGISTRY.put("polltypeTagSchema", "schemas/nips/nip-88/tag/polltype/schema.json");
        REGISTRY.put("responseTagSchema", "schemas/nips/nip-88/tag/response/schema.json");
        REGISTRY.put("kind31989Schema", "schemas/nips/nip-89/kind-31989/schema.json");
        REGISTRY.put("kind31990Schema", "schemas/nips/nip-89/kind-31990/schema.json");
        REGISTRY.put("clientTagSchema", "schemas/nips/nip-89/tag/client/schema.json");
        REGISTRY.put("kind30402Schema", "schemas/nips/nip-99/kind-30402/schema.json");
        REGISTRY.put("kind30403Schema", "schemas/nips/nip-99/kind-30403/schema.json");
        REGISTRY.put("kind10063Schema", "schemas/nips/nip-b7/kind-10063/schema.json");
        REGISTRY.put("kind10051Schema", "schemas/mips/mip-00/kind-10051/schema.json");
        REGISTRY.put("kind443Schema", "schemas/mips/mip-00/kind-443/schema.json");
        REGISTRY.put("encodingTagSchema", "schemas/mips/mip-00/tag/encoding/schema.json");
        REGISTRY.put("mlsciphersuiteTagSchema", "schemas/mips/mip-00/tag/mls_ciphersuite/schema.json");
        REGISTRY.put("mlsextensionsTagSchema", "schemas/mips/mip-00/tag/mls_extensions/schema.json");
        REGISTRY.put("mlsprotocolversionTagSchema", "schemas/mips/mip-00/tag/mls_protocol_version/schema.json");
        REGISTRY.put("kind444Schema", "schemas/mips/mip-02/kind-444/schema.json");
        REGISTRY.put("kind445Schema", "schemas/mips/mip-03/kind-445/schema.json");
        REGISTRY.put("hTagSchema", "schemas/mips/mip-03/tag/h/schema.json");
        REGISTRY.put("messagefilterSchema", "schemas/@/message/filter.json");
        REGISTRY.put("nip05Schema", "schemas/@/nip05.json");
        REGISTRY.put("nostrwellknownSchema", "schemas/@/nostr-well-known.json");
        REGISTRY.put("notekind22242Schema", "schemas/@/note/kind-22242.json");
        REGISTRY.put("noteunsignedSchema", "schemas/@/note-unsigned.json");
        REGISTRY.put("authrelayTagSchema", "schemas/@/tag/auth-relay.json");
        REGISTRY.put("dmrelayTagSchema", "schemas/@/tag/dm-relay.json");
        REGISTRY.put("externalcontentiTagSchema", "schemas/@/tag/external-content-i.json");
        REGISTRY.put("externalcontentkTagSchema", "schemas/@/tag/external-content-k.json");
        REGISTRY.put("gitrefTagSchema", "schemas/@/tag/git-ref.json");
        REGISTRY.put("mip00iTagSchema", "schemas/@/tag/mip-00_i.json");
        REGISTRY.put("mlsclientTagSchema", "schemas/@/tag/mls_client.json");
        REGISTRY.put("reactioneTagSchema", "schemas/@/tag/reaction-e.json");
    }

    public static String get(String key) {
        return CACHE.computeIfAbsent(key, k -> {
            String path = REGISTRY.get(k);
            if (path == null) return null;
            try (InputStream is = Schemata.class.getClassLoader().getResourceAsStream(path)) {
                if (is == null) return null;
                return new String(is.readAllBytes(), StandardCharsets.UTF_8);
            } catch (Exception e) {
                return null;
            }
        });
    }

    public static List<String> keys() {
        List<String> keys = new ArrayList<>(REGISTRY.keySet());
        Collections.sort(keys);
        return keys;
    }
}
